### PR TITLE
Adding some improvements

### PR DESCRIPTION
**Pull request by marcelaraujo**
Adding some improvements!!!

v1.3 - 2013-01-02

Adding new docx format support.
Adding paper size and orientation capable.
Updated the options parser.
Updated contributors.

### CODE REVIEW

**Comment by Ryanb58** [comment]
Why has this not been merged in? JW

**Comment by marcelaraujo** [comment]
This project is deprecated @ryanb58

**Comment by mirkonasato** [comment]
I don't really have time to maintain this project, sorry. Feel free to use @marcelaraujo's branch directly if it works better.

**Comment by Ryanb58** [comment]
Okay. Thank you!

**Comment by marcelaraujo** [comment]
@Ryanb58 You could use this one which is compatible with Python 3 and have more fixes than mine.

https://github.com/tyrannosaurus/pyodconverter

**Pull request closed without merging**
