### PR TITLE
Upgrade to Python 3

### PR DESCRIPTION
**Pull request by antivir88**

### CODE REVIEW

**Comment by mirkonasato** [comment]
Thanks for the patch, but there are lots of changes there, not just upgrading to Python 3. Please provide some description, maybe update the Changelog in the README.

Also, is it a good idea to require Python 3, or are there still Office versions using Python 2.x?

**Comment by antivir88** [comment]
This document is not converted, you can see?
http://dropmefiles.com/Bnyfp

**Comment by antivir88** [comment]
$ /usr/bin/python3 ./../../../../application/extensions/documentConverter/DocumentConverter.py 449d.odt 449d.pdfTraceback (most recent call last):
  File "./../../../../application/extensions/documentConverter/DocumentConverter.py", line 442, in <module>
    converter.convert(args[0], args[1], options.paper_size, options.paper_orientation)
  File "./../../../../application/extensions/documentConverter/DocumentConverter.py", line 313, in convert
    family = self._detectFamily(document)
  File "./../../../../application/extensions/documentConverter/DocumentConverter.py", line 382, in _detectFamily
    if document.supportsService("com.sun.star.text.WebDocument"):
AttributeError: 'NoneType' object has no attribute 'supportsService'
[1]+  Done                    soffice "-accept=socket,host=localhost,port=2002;urp;StarOffice.ServiceManager" -nologo -headless -nofirststartwizard

**Comment by antivir88** [comment]
Yes

**Comment by antivir88** [comment]
Also, is it a good idea to require Python 3, or are there still Office versions using Python 2.x?

Yes

**Comment by sorawa** [comment]
@mirkonasato  this script can't support libreoffice 5.1

**Comment by daveaudy** [comment]
I have used this version of python script successfully with Libre Office 6.0 on Ubunto on Windows 10 and Bash.

**Comment by mirkonasato** [comment]
Superseded by #9

**Pull request closed without merging**
